Try URLConnectionEngine instead of default Apache HttpClient
Note: we cannot exclude the httpclient dependency or we have
NoClassDefFoundError at runtime when loading ResteasyClientBuilder.

Change-Id: I10045e1b1c85e528f1173861c94980f9b20e1222